### ISSUE TITLE
AttributeError: module 'pymc' has no attribute 'diagnostics'

### ISSUE THREAD

**Issue by nullk13** [hddm-devs/kabuki#37]
Looking for help with this error. This is coming up at the end of my code running. 

I think the error stems from the italicized section of the code:
```
from ipyparallel import Client
v = Client()[0:4]
jobs = v.map(HDDMRun_Dep_z,range(4))
wait_watching_stdout(jobs)
Code = jobs.get()
# Bring all of the jobs together
comb_models_z = kabuki.utils.concat_models(Code) 
# Test convergence using Rhat
from kabuki.analyze import gelman_rubin
gelman_rubin(Code)
# Print the stats
comb_models_z.print_stats()
```

The error:
```
Traceback (most recent call last):
 
  File "<ipython-input-5-3d910990c922>", line 152, in <module>
    gelman_rubin(Code)
 
  File "/home/.../python3.6/site-packages/kabuki/analyze.py", line 150, in gelman_rubin
    R_hat_dict[name] = pm.diagnostics.gelman_rubin(samples)
 
**AttributeError: module 'pymc' has no attribute 'diagnostics'**
```

**Comment by nullk13** [comment]
> Looking for help with this error. This is coming up at the end of my code running.
> 
> I think the error stems from the italicized section of the code:
> 
> ```
> from ipyparallel import Client
> v = Client()[0:4]
> jobs = v.map(HDDMRun_Dep_z,range(4))
> wait_watching_stdout(jobs)
> Code = jobs.get()
> # Bring all of the jobs together
> comb_models_z = kabuki.utils.concat_models(Code) 
> # Test convergence using Rhat
> from kabuki.analyze import gelman_rubin
> gelman_rubin(Code)
> # Print the stats
> comb_models_z.print_stats()
> ```
> 
> The error:
> 
> ```
> Traceback (most recent call last):
>  
>   File "<ipython-input-5-3d910990c922>", line 152, in <module>
>     gelman_rubin(Code)
>  
>   File "/home/.../python3.6/site-packages/kabuki/analyze.py", line 150, in gelman_rubin
>     R_hat_dict[name] = pm.diagnostics.gelman_rubin(samples)
>  
> **AttributeError: module 'pymc' has no attribute 'diagnostics'**
> ```

**Comment by twiecki** [comment]
This is odd, what's your pymc version?

**Comment by nullk13** [comment]
pymc is version 2.3.7

**Comment by twiecki** [comment]
Very weird, did you install with conda?

**Comment by moxtoby** [comment]
Have you found a solution for this issue? I've recently installed hddm after lots of trial and error using different package versions, and although I can use hddm.HDDM(data) command to estimate parameters, I can't seem to get gelman_rubin convergence statistic to work. 
I have the same error as the original query ....
My code:
models = [ ]
for i in range(5):
     m = hddm.HDDM(data)
     m.find_starting_values( )
     m.sample(1000, burn=200)
     models.append(m)

from kauki.analyze import gelman_rubin
gelman_rubin(models)

I get the error:
 [-----------------100%-----------------] 1000 of 1000 complete in 27.4 sec

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-9ae2fc93c304> in <module>
      8     models.append(m)
      9 from kabuki.analyze import gelman_rubin
---> 10 hddm.analyze.gelman_rubin(models)

~\anaconda3_new\envs\hddm\lib\site-packages\kabuki\analyze.py in gelman_rubin(models)
    154             samples[i, :] = model.nodes_db.loc[name, "node"].trace()
    155 
--> 156         R_hat_dict[name] = pm.diagnostics.gelman_rubin(samples)
    157 
    158     return R_hat_dict

AttributeError: module 'pymc' has no attribute 'diagnostics'


I am using the following versions (note... they're the only version I can get hddm to install and work):
hddm 0.8.0
pymc 2.3.7
python 3.6.10
pandas 0.20.0
numpy 1.19.2

I am hoping @twiecki can help.

Thank you.
Michelle
